namespace FedExAPI
{
    public enum EnumLabelStockType
    {
        PAPER_4X6,
        PAPER_4X675,
        PAPER_4X8,
        PAPER_4X9,
        PAPER_7X475,
        PAPER_85X11_BOTTOM_HALF_LABEL,
        PAPER_85X11_TOP_HALF_LABEL,
        PAPER_LETTER,
        STOCK_4X675_LEADING_DOC_TAB,
        STOCK_4X8,
        STOCK_4X9_LEADING_DOC_TAB,
        STOCK_4X6,
        STOCK_4X675_TRAILING_DOC_TAB,
        STOCK_4X9_TRAILING_DOC_TAB,
        STOCK_4X9,
        STOCK_4X85_TRAILING_DOC_TAB,
        STOCK_4X105_TRAILING_DOC_TAB
    }
}