namespace FedExAPI
{
    public enum EnumShippingDocumentType
    {
        CERTIFICATE_OF_ORIGIN,
        COMMERCIAL_INVOICE,
        CUSTOM_PACKAGE_DOCUMENT,
        CUSTOM_SHIPMENT_DOCUMENT,
        CUSTOMER_SPECIFIED_LABELS,
        EXPORT_DECLARATION,
        GENERAL_AGENCY_AGREEMENT,
        LABEL,
        USMCA_CERTIFICATION_OF_ORIGIN,
        OP_900,
        PENDING_SHIPMENT_EMAIL_NOTIFICATION,
        PRO_FORMA_INVOICE,
        RETURN_INSTRUCTIONS,
        USMCA_COMMERCIAL_INVOICE_CERTIFICATION_OF_ORIGIN
    }
}